name: Lint Check

on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm i
    
    - name: Run lint
      run: npm run lint
    
    - name: Discord Notification - Success
      if: success()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ✅ **Lint Check Concluído com Sucesso**
          Um ou mais commits foram adicionados e a verificação de lint foi concluída com sucesso!
    
    - name: Discord Notification - Failure
      if: failure()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ❌ **Lint Check Concluído com Falha**
          Um ou mais commits foram adicionados e a verificação de lint foi concluída com **FALHA**!
