name: Jest Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm i
    
    - name: Run tests
      run: npm test
    
    - name: Discord Notification - Success
      if: success()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          {
            "embeds": [
              {
                "title": "✅ Tests Concluído com Sucesso",
                "description": "Um ou mais commits foram adicionados e os testes foram concluídos com sucesso!",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "${{ github.sha }}",
                    "inline": false
                  }
                ],
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            ]
          }
    
    - name: Discord Notification - Failure
      if: failure()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          {
            "embeds": [
              {
                "title": "❌ Tests Concluído com Falha",
                "description": "Um ou mais commits foram adicionados e os testes foram concluídos com FALHA!",
                "color": 15158332,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "${{ github.sha }}",
                    "inline": false
                  }
                ],
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            ]
          }